
package br.com.Views;

import DTO.UsuarioDTO;
import br.com.DAO.ConexaoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class TeladeCadastrodeUsuários extends javax.swing.JFrame {
    
    private ArrayList<UsuarioDTO> listaUsuarios = new ArrayList<>();

    /**
     * Creates new form TeladeCadastrodeUsuários
     */
    public TeladeCadastrodeUsuários() {
        initComponents();
        carregarUsuariosDoBanco();
    }
    
    private void carregarUsuariosDoBanco() {
         try (Connection conn = ConexaoDAO.conector()) {
        if (conn != null) { // Verifica se a conexão foi estabelecida
            String sql = "SELECT * FROM usuarios";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            listaUsuarios.clear(); // Limpa a lista antes de carregar novos usuários

            while (rs.next()) {
                UsuarioDTO usuario = new UsuarioDTO(
                    rs.getString("nome"),
                    rs.getString("email"),
                    rs.getString("nomeDeUsuario"),
                    rs.getString("senha")
                );
                listaUsuarios.add(usuario);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Conexão com o banco de dados falhou!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar usuários do banco de dados: " + e.getMessage());
        e.printStackTrace(); // Para obter detalhes no console
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNomeUsu = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        TextFieldEmail = new javax.swing.JTextField();
        TextFieldNomeUsu = new javax.swing.JTextField();
        PasswordSenha = new javax.swing.JPasswordField();
        btnInserir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblEmail.setText("E-mail");

        lblNomeUsu.setText("Nome de Usuário");

        lblSenha.setText("Senha");

        TextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeActionPerformed(evt);
            }
        });

        TextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEmailActionPerformed(evt);
            }
        });

        TextFieldNomeUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeUsuActionPerformed(evt);
            }
        });

        PasswordSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSenhaActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblSenha)
                            .addComponent(lblEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblNomeUsu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnInserir)
                        .addGap(26, 26, 26)
                        .addComponent(btnEditar)
                        .addGap(13, 13, 13)
                        .addComponent(btnExcluir)
                        .addGap(11, 11, 11)
                        .addComponent(btnCancelar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblNome)
                .addGap(1, 1, 1)
                .addComponent(TextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addGap(1, 1, 1)
                .addComponent(TextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsu)
                .addGap(3, 3, 3)
                .addComponent(TextFieldNomeUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeActionPerformed

    private void TextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEmailActionPerformed

    private void TextFieldNomeUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeUsuActionPerformed

    private void PasswordSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordSenhaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
          String nome = TextFieldNome.getText();
        String email = TextFieldEmail.getText();
        String nomeDeUsuario = TextFieldNomeUsu.getText();
        String senha = new String(PasswordSenha.getPassword());

        if (nome.isEmpty() || nomeDeUsuario.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome, Nome de Usuário e Senha são obrigatórios!");
            return;
        }

        for (UsuarioDTO usuario : listaUsuarios) {
            if (usuario.getUsuario().equals(nomeDeUsuario)) {
                JOptionPane.showMessageDialog(this, "Nome de Usuário já existe!");
                return;
            }
        }

        try (Connection conn = ConexaoDAO.conector()) {
            String sql = "INSERT INTO usuarios (nome, email, nomeDeUsuario, senha) VALUES (?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nome);
            stmt.setString(2, email);
            stmt.setString(3, nomeDeUsuario);
            stmt.setString(4, senha);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Usuário inserido com sucesso!");
            listaUsuarios.add(new UsuarioDTO ("nome", "email", "nomeDeUsuario","senha"));
            limparCampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir usuário no banco de dados: " + e.getMessage());
        }

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         String nomeDeUsuario = TextFieldNomeUsu.getText();

        try (Connection conn = ConexaoDAO.conector()) {
            String sql = "UPDATE usuarios SET nome = ?, email = ?, senha = ? WHERE nomeDeUsuario = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, TextFieldNome.getText());
            stmt.setString(2, TextFieldEmail.getText());
            stmt.setString(3, new String(PasswordSenha.getPassword()));
            stmt.setString(4, nomeDeUsuario);

            if (stmt.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Usuário editado com sucesso!");
                limparCampos();
                carregarUsuariosDoBanco(); // Atualiza a lista local
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar usuário no banco de dados: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
           String nomeDeUsuario = TextFieldNomeUsu.getText();

    if(nomeDeUsuario.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nome de Usuário é obrigatório!");
        return;
    }

    try (Connection conn = ConexaoDAO.conector()) {
        String sql = "DELETE FROM usuarios WHERE nomeDeUsuario = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nomeDeUsuario);

        int deleted = pstmt.executeUpdate();
        if(deleted > 0) {
            JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");

            // Busca e remove o usuário da lista local
            listaUsuarios.removeIf(usuario -> usuario.getUsuario().equals(nomeDeUsuario));
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir usuário: " + e.getMessage());
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          limparCampos();
        JOptionPane.showMessageDialog(this, "Operação cancelada.");
}

private void limparCampos() {
    TextFieldNome.setText("");
    TextFieldEmail.setText("");
    TextFieldNomeUsu.setText("");
    PasswordSenha.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeCadastrodeUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeCadastrodeUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeCadastrodeUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeCadastrodeUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeladeCadastrodeUsuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordSenha;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JTextField TextFieldNomeUsu;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeUsu;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables

   
}
