
package br.com.Views;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        SubMenuCDUsu = new javax.swing.JMenuItem();
        SubMenuCDC = new javax.swing.JMenuItem();
        MenuAgenda = new javax.swing.JMenu();
        SubMenuCompromissos = new javax.swing.JMenuItem();
        SubMenuEventos = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaPrincipal");
        setResizable(false);

        MenuCadastro.setText("Cadastro");

        SubMenuCDUsu.setText("Cadastro de Usuários");
        SubMenuCDUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuCDUsuActionPerformed(evt);
            }
        });
        MenuCadastro.add(SubMenuCDUsu);

        SubMenuCDC.setText("Cadastro de Clientes");
        SubMenuCDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuCDCActionPerformed(evt);
            }
        });
        MenuCadastro.add(SubMenuCDC);

        jMenuBar1.add(MenuCadastro);

        MenuAgenda.setText("Agenda");

        SubMenuCompromissos.setText("compromissos");
        SubMenuCompromissos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuCompromissosActionPerformed(evt);
            }
        });
        MenuAgenda.add(SubMenuCompromissos);

        SubMenuEventos.setText("eventos");
        SubMenuEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuEventosActionPerformed(evt);
            }
        });
        MenuAgenda.add(SubMenuEventos);

        jMenuBar1.add(MenuAgenda);

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuCDUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuCDUsuActionPerformed
          // Crie uma nova instância da tela de cadastro de usuário
    TeladeCadastrodeUsuários teladeCadastrodeUsuários = new TeladeCadastrodeUsuários();
    
    // Defina a visibilidade da tela de cadastro como verdadeira
    teladeCadastrodeUsuários.setVisible(true);
    }//GEN-LAST:event_SubMenuCDUsuActionPerformed

    private void SubMenuCDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuCDCActionPerformed
        TeladeCadastrodeClientes teladeCadastrodeClientes = new TeladeCadastrodeClientes();
    
    // Defina a visibilidade da tela de cadastro como verdadeira
    teladeCadastrodeClientes.setVisible(true);
        
    }//GEN-LAST:event_SubMenuCDCActionPerformed

    private void SubMenuCompromissosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuCompromissosActionPerformed
        TelaAgenda telaAgenda = new TelaAgenda();
    
    // Defina a visibilidade da tela de cadastro como verdadeira
    telaAgenda.setVisible(true);
        
    }//GEN-LAST:event_SubMenuCompromissosActionPerformed

    private void SubMenuEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuEventosActionPerformed
        TelaAgenda telaAgenda = new TelaAgenda();
    
    // Defina a visibilidade da tela de cadastro como verdadeira
    telaAgenda.setVisible(true);
    }//GEN-LAST:event_SubMenuEventosActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
         // Fecha a tela principal
    this.dispose(); // Fecha a janela atual (tela principal)
    
    // Abre a tela de login
    TelaLogin telaLogin = new TelaLogin();
    telaLogin.setVisible(true);
    }//GEN-LAST:event_MenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAgenda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem SubMenuCDC;
    private javax.swing.JMenuItem SubMenuCDUsu;
    private javax.swing.JMenuItem SubMenuCompromissos;
    private javax.swing.JMenuItem SubMenuEventos;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
