
package br.com.View;

import br.com.DAO.UsuarioDAO;
import br.com.DTO.UsuarioDTO;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Vieira
 */
public class CadUsu extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadUsu
     */
    public CadUsu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloUsuarios = new javax.swing.JLabel();
        lblNomeUsu = new javax.swing.JLabel();
        lblIDUsu = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblEmailUsu = new javax.swing.JLabel();
        lblNomeDUsu = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtNomeUsu = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/cosmosBack.jpg"));
        Image img= icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img,0,0,getWidth(),getHeight(), this);
            }
        };
        lblTituloFID = new javax.swing.JLabel();
        btnEditarIDUsu = new javax.swing.JButton();
        btnPesquisarIDUsu = new javax.swing.JButton();
        btnDeletarIDUsu = new javax.swing.JButton();
        btnCriarUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 102));
        setBorder(null);
        setClosable(true);
        setTitle("Usuarios");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTituloUsuarios.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        lblTituloUsuarios.setForeground(new java.awt.Color(255, 255, 0));
        lblTituloUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloUsuarios.setText("Usuarios ");

        lblNomeUsu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNomeUsu.setForeground(new java.awt.Color(255, 204, 0));
        lblNomeUsu.setText("Nome");

        lblIDUsu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIDUsu.setForeground(new java.awt.Color(255, 204, 0));
        lblIDUsu.setText("ID");

        txtId.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        lblEmailUsu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmailUsu.setForeground(new java.awt.Color(255, 204, 0));
        lblEmailUsu.setText("e-mail");

        lblNomeDUsu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNomeDUsu.setForeground(new java.awt.Color(255, 204, 0));
        lblNomeDUsu.setText("nome de usuario");

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 204, 0));
        lblSenha.setText("senha");

        txtNome.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txtMail.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txtNomeUsu.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txtPass.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jDesktopPane1.setBackground(new java.awt.Color(102, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));

        lblTituloFID.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        lblTituloFID.setForeground(new java.awt.Color(255, 255, 0));
        lblTituloFID.setText("Funções por ID");

        btnEditarIDUsu.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarIDUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarIDUsu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\editar.png")); // NOI18N
        btnEditarIDUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIDUsuActionPerformed(evt);
            }
        });

        btnPesquisarIDUsu.setBackground(new java.awt.Color(255, 255, 0));
        btnPesquisarIDUsu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\pesquisa.png")); // NOI18N
        btnPesquisarIDUsu.setMaximumSize(new java.awt.Dimension(75, 51));
        btnPesquisarIDUsu.setMinimumSize(new java.awt.Dimension(75, 51));
        btnPesquisarIDUsu.setPreferredSize(new java.awt.Dimension(75, 51));
        btnPesquisarIDUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarIDUsuActionPerformed(evt);
            }
        });

        btnDeletarIDUsu.setBackground(new java.awt.Color(255, 255, 0));
        btnDeletarIDUsu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\excluir.png")); // NOI18N
        btnDeletarIDUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarIDUsuActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(lblTituloFID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEditarIDUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnPesquisarIDUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnDeletarIDUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblTituloFID, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarIDUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarIDUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarIDUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloFID)
                .addGap(18, 18, 18)
                .addComponent(btnEditarIDUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnDeletarIDUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnPesquisarIDUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        btnCriarUsuario.setBackground(new java.awt.Color(153, 0, 204));
        btnCriarUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\adicionar-cliente.png")); // NOI18N
        btnCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIDUsu)
                                .addComponent(lblEmailUsu)
                                .addComponent(lblNomeDUsu)
                                .addComponent(lblSenha)
                                .addComponent(lblNomeUsu)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnCriarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIDUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmailUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeDUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jDesktopPane1)
        );

        setBounds(0, 0, 909, 509);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarIDUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIDUsuActionPerformed

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de nome.");
        } else if (txtMail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de Email");
        } else if (txtNomeUsu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de nome de usuario");
        } else if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de senha");
        } else {

            int idUsu = Integer.parseInt(txtId.getText());
            String nomeUsu = txtNome.getText();
            String mailUsu = txtMail.getText();
            String nome_usuarioUsu = txtNomeUsu.getText();
            String pass = txtPass.getText();

            UsuarioDTO dto = new UsuarioDTO();

            dto.setId(idUsu);
            dto.setNome(nomeUsu);
            dto.setEmail(mailUsu);
            dto.setNome_usuario(nome_usuarioUsu);
            dto.setSenha(pass);

            UsuarioDAO dao = new UsuarioDAO();
            dao.atualizar(dto);

        }
    }//GEN-LAST:event_btnEditarIDUsuActionPerformed

    private void btnDeletarIDUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarIDUsuActionPerformed

        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um ID a ser deletado");
        } else {
            UsuarioDTO dto = new UsuarioDTO();

            int idUsu = Integer.parseInt(txtId.getText());

            dto.setId(idUsu);

            UsuarioDAO dao = new UsuarioDAO();
            dao.deletar(dto);
        }
    }//GEN-LAST:event_btnDeletarIDUsuActionPerformed

    private void btnCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarUsuarioActionPerformed

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de nome");
        } else if (txtMail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de email");
        } else if (txtNomeUsu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de nome de usuario");
        } else if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de senha");
        } else if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a area de ID");
        } else {

            int IdUsu = Integer.parseInt(txtId.getText());
            String nomeUsu = txtNome.getText();
            String mailUsu = txtMail.getText();
            String nome_usuarioUsu = txtNomeUsu.getText();
            String pass = txtPass.getText();

            UsuarioDTO dto = new UsuarioDTO();

            dto.setId(IdUsu);
            dto.setNome(nomeUsu);
            dto.setEmail(mailUsu);
            dto.setNome_usuario(nome_usuarioUsu);
            dto.setSenha(pass);

            UsuarioDAO dao = new UsuarioDAO();
            dao.criar(dto);
        }
    }//GEN-LAST:event_btnCriarUsuarioActionPerformed

    private void btnPesquisarIDUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarIDUsuActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o ID a ser pesquisado");
        } else {

            UsuarioDTO dto = new UsuarioDTO();

            int idUsu = Integer.parseInt(txtId.getText());
            dto.setId(idUsu);

            UsuarioDAO dao = new UsuarioDAO();
            dao.pesquisar(dto);

        }
    }//GEN-LAST:event_btnPesquisarIDUsuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarUsuario;
    private javax.swing.JButton btnDeletarIDUsu;
    private javax.swing.JButton btnEditarIDUsu;
    private javax.swing.JButton btnPesquisarIDUsu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblEmailUsu;
    private javax.swing.JLabel lblIDUsu;
    private javax.swing.JLabel lblNomeDUsu;
    private javax.swing.JLabel lblNomeUsu;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTituloFID;
    private javax.swing.JLabel lblTituloUsuarios;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtMail;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextField txtNomeUsu;
    public static javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
