
package br.com.View;

import br.com.DAO.ConexaoDAO;
import br.com.DAO.UsuarioDAO;
import br.com.DTO.UsuarioDTO;
import static br.com.View.CadUsu.txtMail;
import static br.com.View.CadUsu.txtNome;
import static br.com.View.CadUsu.txtNomeUsu;
import static br.com.View.CadUsu.txtPass;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Vieira
 */
public class CriaUsu extends javax.swing.JFrame {

    /**
     * Creates new form CriaUsu
     */
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public CriaUsu() {
        initComponents();
        conexao= ConexaoDAO.connector();
    }
    
    public void criar() {
        String sql = "insert into tb_usuarios (nome, email, nome_usuario, senha) values(?, ?, ?, ?)";
        try {
            pst = conexao.prepareStatement(sql);

            if (txtNomeRegistrar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha a area de nome.");
            } else if (txtEmailRegistrar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha a area de Email");
            } else if (txtNomeUsuRegistrar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha a area de nome de usuario");
            } else if (txtPassRegistrar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha a area de senha");
            } else {
                pst.setString(1, txtNomeRegistrar.getText());
                pst.setString(2, txtEmailRegistrar.getText());
                pst.setString(3, txtNomeUsuRegistrar.getText());
                pst.setString(4, txtPassRegistrar.getText());
            }

            int add = pst.executeUpdate();

            if (add > 0) {
                JOptionPane.showMessageDialog(null, "Adicionado com sucesso");
                TelaPrincipal TP = new TelaPrincipal();
                TP.setVisible(true);
                this.dispose();
            }

        } catch (Exception e) {
            if (e.getMessage().contains("tb_usuarios.nome_usuario")) {
                JOptionPane.showMessageDialog(null, "Nome de usuario ja em uso.");
            } else if (e.getMessage().contains("tb_usuarios.email")) {
                JOptionPane.showMessageDialog(null, "email ja em uso");
            } else {
                JOptionPane.showMessageDialog(null, "metodo criar " + e);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRegistresuaConta = new javax.swing.JLabel();
        txtPassRegistrar = new javax.swing.JTextField();
        btnCriarConta = new javax.swing.JButton();
        lblNomeNovo = new javax.swing.JLabel();
        lblEmailNovo = new javax.swing.JLabel();
        lblNomeDUsuNovo = new javax.swing.JLabel();
        lblSenhaNova = new javax.swing.JLabel();
        txtNomeRegistrar = new javax.swing.JTextField();
        txtEmailRegistrar = new javax.swing.JTextField();
        txtNomeUsuRegistrar = new javax.swing.JTextField();
        lblIDDUsuNovo = new javax.swing.JLabel();
        txtIdRegistrar = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("criar usuario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblTituloRegistresuaConta.setBackground(new java.awt.Color(102, 0, 102));
        lblTituloRegistresuaConta.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblTituloRegistresuaConta.setForeground(new java.awt.Color(255, 255, 0));
        lblTituloRegistresuaConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistresuaConta.setText("Registre sua conta!");

        txtPassRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassRegistrarActionPerformed(evt);
            }
        });

        btnCriarConta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\adicionar-cliente.png")); // NOI18N
        btnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContaActionPerformed(evt);
            }
        });

        lblNomeNovo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeNovo.setForeground(new java.awt.Color(102, 0, 102));
        lblNomeNovo.setText("Nome");

        lblEmailNovo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmailNovo.setForeground(new java.awt.Color(102, 0, 102));
        lblEmailNovo.setText("e-mail");

        lblNomeDUsuNovo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeDUsuNovo.setForeground(new java.awt.Color(102, 0, 102));
        lblNomeDUsuNovo.setText("nome de usuario");

        lblSenhaNova.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSenhaNova.setForeground(new java.awt.Color(102, 0, 102));
        lblSenhaNova.setText("senha da conta");

        txtNomeRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRegistrarActionPerformed(evt);
            }
        });

        lblIDDUsuNovo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblIDDUsuNovo.setForeground(new java.awt.Color(102, 0, 102));
        lblIDDUsuNovo.setText("Id de usuario:");

        btnVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\deixou.png")); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmailNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmailRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeDUsuNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeUsuRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblSenhaNova)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTituloRegistresuaConta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIDDUsuNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTituloRegistresuaConta)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeNovo)
                            .addComponent(txtNomeRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailNovo)
                            .addComponent(txtEmailRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeUsuRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeDUsuNovo))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSenhaNova)
                            .addComponent(txtPassRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDDUsuNovo)
                    .addComponent(btnCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
         if(txtNomeRegistrar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha a area de nome");
            } else if(txtEmailRegistrar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha a area de email");
            } else if(txtNomeUsuRegistrar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha a area de nome de usuario");
            } else if(txtPassRegistrar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha a area de senha");
            } else if(txtIdRegistrar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha a area de ID");
            } else {
        
                int idUsu = Integer.parseInt(txtIdRegistrar.getText());
                String nomeUsu= txtNomeRegistrar.getText();
                String mailUsu= txtEmailRegistrar.getText();
                String nome_usuarioUsu= txtNomeUsuRegistrar.getText();
                String pass= txtPassRegistrar.getText();
                
                UsuarioDTO dto = new UsuarioDTO();
                
                dto.setId(idUsu);
                dto.setNome(nomeUsu);
                dto.setEmail(mailUsu);
                dto.setNome_usuario(nome_usuarioUsu);
                dto.setSenha(pass);
                
                
                UsuarioDAO dao= new UsuarioDAO();
                int go = dao.criarAoLogar(dto);
                if (go>0){
                    this.dispose();
                }
                
            }
    }//GEN-LAST:event_btnCriarContaActionPerformed

    private void txtNomeRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRegistrarActionPerformed

    private void txtPassRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassRegistrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicial ini = new TelaInicial();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriaUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblEmailNovo;
    private javax.swing.JLabel lblIDDUsuNovo;
    private javax.swing.JLabel lblNomeDUsuNovo;
    private javax.swing.JLabel lblNomeNovo;
    private javax.swing.JLabel lblSenhaNova;
    private javax.swing.JLabel lblTituloRegistresuaConta;
    private javax.swing.JTextField txtEmailRegistrar;
    private javax.swing.JTextField txtIdRegistrar;
    private javax.swing.JTextField txtNomeRegistrar;
    private javax.swing.JTextField txtNomeUsuRegistrar;
    private javax.swing.JTextField txtPassRegistrar;
    // End of variables declaration//GEN-END:variables
}
