
package br.com.View;

import br.com.DAO.AgendaDAO;
import br.com.DTO.AgendaDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Vieira
 */
public class TelaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        AgendaDAO dao = new AgendaDAO();
        dao.AutoPesquisar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblDataAgenda = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAgendaCli = new javax.swing.JTable();
        txtHora = new javax.swing.JTextField();
        lblHorarioAgenda = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        lblTituloAgendaCli = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblDescricaoAgenda = new javax.swing.JLabel();
        lblIDAgenda = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNomeCliAgenda = new javax.swing.JLabel();
        txtNomeCli = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        lblDataAgenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDataAgenda.setForeground(new java.awt.Color(255, 255, 0));
        lblDataAgenda.setText("data");

        tbAgendaCli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbAgendaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "data", "hora", "descrição", "cliente"
            }
        ));
        jScrollPane1.setViewportView(tbAgendaCli);

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        lblHorarioAgenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHorarioAgenda.setForeground(new java.awt.Color(255, 255, 0));
        lblHorarioAgenda.setText("horario");

        btnAdd.setBackground(new java.awt.Color(255, 255, 0));
        btnAdd.setForeground(new java.awt.Color(255, 204, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/create.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnOut.setBackground(new java.awt.Color(255, 255, 0));
        btnOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\deixou.png")); // NOI18N
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        lblTituloAgendaCli.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblTituloAgendaCli.setForeground(new java.awt.Color(255, 255, 0));
        lblTituloAgendaCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAgendaCli.setText("Agenda de Clientes");

        lblDescricaoAgenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescricaoAgenda.setForeground(new java.awt.Color(255, 255, 0));
        lblDescricaoAgenda.setText("descrição:");

        lblIDAgenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIDAgenda.setForeground(new java.awt.Color(255, 255, 0));
        lblIDAgenda.setText("id da agenda");

        lblNomeCliAgenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNomeCliAgenda.setForeground(new java.awt.Color(255, 255, 0));
        lblNomeCliAgenda.setText("nome do cliente");

        btnEdit.setBackground(new java.awt.Color(255, 255, 0));
        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\editar.png")); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 255, 0));
        btnRemove.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joel\\Desktop\\POO2\\projetofinal\\src\\img\\excluir.png")); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("/");

        jLabel9.setBackground(new java.awt.Color(255, 153, 0));
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("/");

        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText(":");

        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblDataAgenda)
                                            .addGap(10, 10, 10)
                                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel8)
                                            .addGap(4, 4, 4)
                                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel9)
                                            .addGap(6, 6, 6)
                                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblHorarioAgenda)
                                            .addGap(4, 4, 4)
                                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel10)
                                            .addGap(4, 4, 4)
                                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14)
                                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblIDAgenda)
                                        .addComponent(lblNomeCliAgenda))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDescricaoAgenda)
                                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(263, 263, 263)
                                    .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblTituloAgendaCli)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTituloAgendaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblDescricaoAgenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDAgenda)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeCliAgenda)
                            .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataAgenda)
                                    .addComponent(jLabel8))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHorarioAgenda)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Atribua um id a agenda");
        } else if (txtNomeCli.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Atribua um cliente a agenda");
        } else if (txtAno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um ano");
        } else if (txtMes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um mês");
        } else if (txtDia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um dia");
        } else if (txtHora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira uma hora");
        } else if (txtMin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira uma minutagem");
        } else {

            int id = Integer.parseInt(txtId.getText());
            String nomeCli = txtNomeCli.getText();
            String d, m, a, hor, min;
            d = txtDia.getText();
            m = txtMes.getText();
            a = txtAno.getText();
            hor = txtHora.getText();
            min = txtMin.getText();
            String data = a + "-" + m + "-" + d;
            String hora = hor + ":" + min + ":00";
            String desc = txtDesc.getText();

            AgendaDTO dto = new AgendaDTO();
            dto.setId(id);
            dto.setNome_cli(nomeCli);
            dto.setData(data);
            dto.setHora(hora);
            dto.setDescricao(desc);

            AgendaDAO dao = new AgendaDAO();
            dao.adicionar(dto);

            dao.AutoPesquisar();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        TelaPrincipal pri = new TelaPrincipal();
        pri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOutActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Atribua um id a agenda");
        } else if (txtNomeCli.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Atribua um cliente a agenda");
        } else if (txtAno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um ano");
        } else if (txtMes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um mês");
        } else if (txtDia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um dia");
        } else if (txtHora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira uma hora");
        } else if (txtMin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira uma minutagem");
        } else {
            AgendaDAO dao = new AgendaDAO();
            AgendaDTO dto = new AgendaDTO();

            int id = Integer.parseInt(txtId.getText());
            String nomeCli = txtNomeCli.getText();
            String d, m, a, hor, min;
            d = txtDia.getText();
            m = txtMes.getText();
            a = txtAno.getText();
            hor = txtHora.getText();
            min = txtMin.getText();
            String data = a + "-" + m + "-" + d;
            String hora = hor + ":" + min + ":00";
            String desc = txtDesc.getText();

            dto.setId(id);
            dto.setNome_cli(nomeCli);
            dto.setData(data);
            dto.setHora(hora);
            dto.setDescricao(desc);

            dao.atualizar(dto);

            dao.AutoPesquisar();

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
      if(txtId.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Insira o id de um evento a ser deletado");
      } else {
        
       AgendaDAO dao = new AgendaDAO();
       AgendaDTO dto = new AgendaDTO();
       
       int id = Integer.parseInt(txtId.getText());
       dto.setId(id);
       dao.deletar(dto);
       
       dao.AutoPesquisar();
      }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnRemove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataAgenda;
    private javax.swing.JLabel lblDescricaoAgenda;
    private javax.swing.JLabel lblHorarioAgenda;
    private javax.swing.JLabel lblIDAgenda;
    private javax.swing.JLabel lblNomeCliAgenda;
    private javax.swing.JLabel lblTituloAgendaCli;
    public static javax.swing.JTable tbAgendaCli;
    public static javax.swing.JTextField txtAno;
    public static javax.swing.JTextField txtDesc;
    public static javax.swing.JTextField txtDia;
    public static javax.swing.JTextField txtHora;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtMes;
    public static javax.swing.JTextField txtMin;
    public static javax.swing.JTextField txtNomeCli;
    // End of variables declaration//GEN-END:variables
}
